---
framework: mocha
tier: small

postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
   
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version : 2a.0.1
