---
framework: mocha
tier: small

postMerge:
  pattern: 
    - "./test/**/*.spec.ts"
   
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
     env:
      GLOAR_VARIABLE: es-ES
      ENGLISHCODE: ${{ secrets.ENGLISHCODE }}
      INTVALUE: ${{ secrets.Int_value }}
      
postRun:
     command:
        - node --version
version : 2.0.1
